import React, { useState, useMemo } from 'react';
import { findSyncMapping, buildSyncInfo, TARGET_REPOS, type SyncInfo } from '../data/sync-mappings';
import { getStoredToken, storeToken, clearToken, createDesignSyncPR } from '../utils/github';

interface CheckItem {
  category: string;
  property: string;
  figmaValue: string;
  figmaToken?: string;
  codeValue: string;
  codeToken?: string;
  status: 'match' | 'mismatch' | 'missing';
}

interface DesignCheckResult {
  component: string;
  platform: 'web' | 'ios';
  summary: { total: number; match: number; mismatch: number; matchRate: number };
  items: CheckItem[];
}

interface MismatchInfo {
  platform: string;
  item: CheckItem;
  syncInfo: SyncInfo;
}

function collectMismatches(component: string, results: DesignCheckResult[]): MismatchInfo[] {
  const mismatches: MismatchInfo[] = [];
  for (const result of results) {
    for (const item of result.items) {
      if (item.status !== 'mismatch') continue;
      const mapping = findSyncMapping(item.codeToken, item.property, result.platform);
      if (mapping) {
        const syncInfo = buildSyncInfo(mapping, item.property, item.codeToken || '', item.codeValue, item.figmaValue, component);
        mismatches.push({ platform: result.platform, item, syncInfo });
      }
    }
  }
  return mismatches;
}

type PRStatus = 'idle' | 'token-input' | 'creating' | 'success' | 'error';

export function CreateFixPRButton({ component, results }: { component: string; results: DesignCheckResult[] }) {
  const [open, setOpen] = useState(false);
  const [status, setStatus] = useState<PRStatus>('idle');
  const [tokenInput, setTokenInput] = useState('');
  const [prUrls, setPrUrls] = useState<string[]>([]);
  const [error, setError] = useState('');

  const mismatches = useMemo(() => collectMismatches(component, results), [component, results]);

  // Group by repo
  const byRepo = useMemo(() => {
    const map = new Map<string, MismatchInfo[]>();
    for (const m of mismatches) {
      const list = map.get(m.syncInfo.repo) || [];
      list.push(m);
      map.set(m.syncInfo.repo, list);
    }
    return map;
  }, [mismatches]);

  const repoLabels = useMemo(
    () => [...byRepo.keys()].map((r) => TARGET_REPOS[r as keyof typeof TARGET_REPOS]?.label || r).join(', '),
    [byRepo],
  );

  if (mismatches.length === 0) return null;

  const handleClick = () => {
    const token = getStoredToken();
    if (token) {
      setOpen(true);
      setStatus('idle');
    } else {
      setOpen(true);
      setStatus('token-input');
    }
  };

  const handleTokenSave = () => {
    if (!tokenInput.trim()) return;
    storeToken(tokenInput.trim());
    setTokenInput('');
    setStatus('idle');
  };

  const handleCreatePR = async () => {
    const token = getStoredToken();
    if (!token) {
      setStatus('token-input');
      return;
    }

    setStatus('creating');
    setError('');
    setPrUrls([]);

    const date = new Date().toISOString().split('T')[0];
    const urls: string[] = [];

    try {
      for (const [repoKey, repoMismatches] of byRepo) {
        const repoConfig = TARGET_REPOS[repoKey as keyof typeof TARGET_REPOS];
        if (!repoConfig) continue;

        const branchName = `fix/design-sync-${component.toLowerCase()}-${date}`;

        // Group changes by file path, dedup
        const fileChanges = new Map<string, { currentValue: string; newValue: string }[]>();
        for (const m of repoMismatches) {
          const list = fileChanges.get(m.syncInfo.filePath) || [];
          list.push({ currentValue: m.syncInfo.currentValue, newValue: m.syncInfo.expectedValue });
          fileChanges.set(m.syncInfo.filePath, list);
        }

        // Build changes array (one entry per unique file+value pair)
        const changes = [...fileChanges.entries()].flatMap(([path, vals]) =>
          vals.map((v) => ({ path, currentValue: v.currentValue, newValue: v.newValue })),
        );

        // Build PR body
        const bodyLines = [
          `## Design Sync Fix: ${component}`,
          '',
          `Figma-Code mismatch 자동 수정`,
          '',
          '### Changes',
          '',
          '| Property | Before | After | File |',
          '|----------|--------|-------|------|',
          ...repoMismatches.map((m) =>
            `| ${m.item.property} | \`${m.syncInfo.currentValue}\` | \`${m.syncInfo.expectedValue}\` | \`${m.syncInfo.filePath}\` |`,
          ),
          '',
          '> Auto-generated by MRT Design System Progress Board',
        ];

        const prUrl = await createDesignSyncPR({
          token,
          owner: repoConfig.owner,
          repo: repoConfig.repo,
          branch: branchName,
          title: `fix(tokens): sync ${component} design tokens with Figma`,
          body: bodyLines.join('\n'),
          changes,
        });

        urls.push(prUrl);
      }

      setPrUrls(urls);
      setStatus('success');
    } catch (e: any) {
      setError(e.message || 'PR 생성 실패');
      if (e.message?.includes('401') || e.message?.includes('403')) {
        clearToken();
        setError('GitHub 토큰이 유효하지 않습니다. 다시 입력해주세요.');
        setStatus('token-input');
      } else {
        setStatus('error');
      }
    }
  };

  return (
    <div>
      <button
        onClick={handleClick}
        className="inline-flex items-center gap-1.5 text-xs font-medium px-3 py-1.5 rounded-lg bg-blue-600 text-white hover:bg-blue-700 transition-colors"
      >
        <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
        </svg>
        PR 생성 ({mismatches.length} fixes)
      </button>

      {open && (
        <div className="mt-3 border border-gray-200 rounded-lg bg-white shadow-sm overflow-hidden">
          {/* Header */}
          <div className="px-4 py-3 bg-gray-50 border-b border-gray-200">
            <div className="flex items-center justify-between">
              <h3 className="text-sm font-semibold text-gray-800">
                {component} — Design Sync PR
              </h3>
              <button onClick={() => { setOpen(false); setStatus('idle'); }} className="text-gray-400 hover:text-gray-600 text-lg leading-none">&times;</button>
            </div>
            <p className="text-xs text-gray-500 mt-1">
              {mismatches.length}개 mismatch &rarr; <span className="font-medium text-gray-700">{repoLabels}</span>
            </p>
          </div>

          <div className="px-4 py-4 space-y-3">
            {/* Token input */}
            {status === 'token-input' && (
              <div className="space-y-2">
                <label className="text-xs font-medium text-gray-700">GitHub Personal Access Token</label>
                <p className="text-xs text-gray-400">
                  repo 권한이 필요합니다. 브라우저 localStorage에만 저장됩니다.
                </p>
                <div className="flex gap-2">
                  <input
                    type="password"
                    value={tokenInput}
                    onChange={(e) => setTokenInput(e.target.value)}
                    placeholder="ghp_xxxxxxxxxxxx"
                    className="flex-1 text-xs px-3 py-1.5 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent"
                    onKeyDown={(e) => e.key === 'Enter' && handleTokenSave()}
                  />
                  <button
                    onClick={handleTokenSave}
                    disabled={!tokenInput.trim()}
                    className="text-xs font-medium px-3 py-1.5 rounded-lg bg-gray-900 text-white hover:bg-gray-800 disabled:opacity-40 transition-colors"
                  >
                    저장
                  </button>
                </div>
              </div>
            )}

            {/* Mismatch preview */}
            {(status === 'idle' || status === 'error') && (
              <>
                <div className="overflow-x-auto rounded-lg border border-gray-200">
                  <table className="w-full text-xs">
                    <thead>
                      <tr className="bg-gray-50 border-b border-gray-200">
                        <th className="text-left px-3 py-1.5 font-medium text-gray-600">Property</th>
                        <th className="text-left px-3 py-1.5 font-medium text-gray-600">Before</th>
                        <th className="text-left px-3 py-1.5 font-medium text-gray-600">After</th>
                        <th className="text-left px-3 py-1.5 font-medium text-gray-600">Repo</th>
                      </tr>
                    </thead>
                    <tbody>
                      {mismatches.map((m, i) => (
                        <tr key={i} className="border-b border-gray-100 last:border-0">
                          <td className="px-3 py-1.5 font-mono text-gray-700">{m.item.property}</td>
                          <td className="px-3 py-1.5"><code className="text-red-600">{m.syncInfo.currentValue}</code></td>
                          <td className="px-3 py-1.5"><code className="text-green-600">{m.syncInfo.expectedValue}</code></td>
                          <td className="px-3 py-1.5 text-gray-400">{TARGET_REPOS[m.syncInfo.repo as keyof typeof TARGET_REPOS]?.label}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>

                {error && (
                  <div className="text-xs text-red-600 bg-red-50 border border-red-200 rounded-lg px-3 py-2">
                    {error}
                  </div>
                )}

                <div className="flex items-center gap-2">
                  <button
                    onClick={handleCreatePR}
                    className="inline-flex items-center gap-1.5 text-xs font-medium px-4 py-2 rounded-lg bg-green-600 text-white hover:bg-green-700 transition-colors"
                  >
                    <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                    GitHub에 PR 생성
                  </button>
                  {getStoredToken() && (
                    <button
                      onClick={() => { clearToken(); setStatus('token-input'); }}
                      className="text-xs text-gray-400 hover:text-gray-600"
                    >
                      토큰 변경
                    </button>
                  )}
                </div>
              </>
            )}

            {/* Creating */}
            {status === 'creating' && (
              <div className="flex items-center gap-2 text-sm text-gray-600 py-4">
                <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                </svg>
                PR 생성 중...
              </div>
            )}

            {/* Success */}
            {status === 'success' && (
              <div className="space-y-2">
                <div className="flex items-center gap-2 text-sm text-green-700">
                  <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  PR 생성 완료!
                </div>
                {prUrls.map((url, i) => (
                  <a
                    key={i}
                    href={url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="block text-xs text-blue-600 hover:underline break-all"
                  >
                    {url}
                  </a>
                ))}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
