/**
 * GitHub API 클라이언트
 * PR 생성 + 파일 커밋
 */

export interface GitHubConfig {
  token: string;
  owner: string;
  repo: string;
}

interface FileChange {
  path: string;
  content: string; // base64
}

export async function createApprovePR(
  config: GitHubConfig,
  candidateId: string,
  files: FileChange[]
): Promise<string> {
  const branchName = `ds/approve-${candidateId}-${Date.now()}`;
  const base = 'main';

  // 1. main 브랜치 최신 SHA
  const mainRef = await ghFetch(config, `git/refs/heads/${base}`);
  const baseSha: string = mainRef.object.sha;

  // 2. 새 브랜치 생성
  await ghFetch(config, 'git/refs', 'POST', {
    ref: `refs/heads/${branchName}`,
    sha: baseSha,
  });

  // 3. 파일 blob 생성 → tree 구성
  const treeItems = await Promise.all(
    files.map(async (f) => {
      const blob = await ghFetch(config, 'git/blobs', 'POST', {
        content: f.content,
        encoding: 'base64',
      });
      return {
        path: f.path,
        mode: '100644',
        type: 'blob',
        sha: blob.sha,
      };
    })
  );

  // 4. 새 tree 생성
  const tree = await ghFetch(config, 'git/trees', 'POST', {
    base_tree: baseSha,
    tree: treeItems,
  });

  // 5. 커밋 생성
  const commit = await ghFetch(config, 'git/commits', 'POST', {
    message: `feat(ds): ${candidateId} 컴포넌트 DS 정식 편입\n\n- candidates.ts status: in-progress → completed\n- packages/ui/src/components/${toPascalCase(candidateId)}/ 스캐폴딩 생성\n\nApproved via MRT DS Candidate Sync (Figma Plugin)`,
    tree: tree.sha,
    parents: [baseSha],
  });

  // 6. 브랜치 업데이트
  await ghFetch(config, `git/refs/heads/${branchName}`, 'PATCH', {
    sha: commit.sha,
    force: false,
  });

  // 7. PR 생성
  const pr = await ghFetch(config, 'pulls', 'POST', {
    title: `feat(ds): ${candidateId} DS 정식 편입`,
    body: buildPRBody(candidateId),
    head: branchName,
    base,
  });

  return pr.html_url as string;
}

async function ghFetch(
  config: GitHubConfig,
  endpoint: string,
  method = 'GET',
  body?: unknown
): Promise<Record<string, unknown>> {
  const res = await fetch(`https://api.github.com/repos/${config.owner}/${config.repo}/${endpoint}`, {
    method,
    headers: {
      Authorization: `Bearer ${config.token}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
      'X-GitHub-Api-Version': '2022-11-28',
    },
    body: body ? JSON.stringify(body) : undefined,
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`GitHub API ${method} ${endpoint} 실패 (${res.status}): ${err}`);
  }
  return res.json() as Promise<Record<string, unknown>>;
}

function toPascalCase(str: string): string {
  return str
    .split(/[-_]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

function buildPRBody(candidateId: string): string {
  const pascal = toPascalCase(candidateId);
  return `## DS 후보군 정식 편입: \`${candidateId}\`

> Figma Plugin **MRT DS Candidate Sync**에서 디자이너 승인 후 자동 생성된 PR

### 변경 사항

- \`packages/mcp-server/src/tools/candidates.ts\` — status \`in-progress\` → \`completed\`
- \`packages/ui/src/components/${pascal}/${pascal}.tsx\` — 컴포넌트 스캐폴딩
- \`packages/ui/src/components/${pascal}/${pascal}.types.ts\` — Props 타입 정의

### 다음 단계

- [ ] 컴포넌트 구현 완성 (\`${pascal}.tsx\`)
- [ ] Storybook stories 작성 (\`${pascal}.stories.tsx\`)
- [ ] ai-index 재빌드 → MCP tool 자동 인식
- [ ] 디자이너 Figma 컴포넌트와 토큰 연결 확인

🤖 Generated by MRT DS Candidate Sync (Figma Plugin)
`;
}
